### ISSUE TITLE
Add attribution to Pedro Vicente Gómez Sánchez

### ISSUE THREAD

**Issue by joseantoniosantos** [tonilopezmr/InteractorExecutor#1]
Hi!

I see in your code you have some **_"Documented by Pedro Vicente Gómez Sánchez"**_ notes in your javadoc. I've reviewed why your code has been documented and @pedrovgs you code is really similar to the one you can find in this repository https://github.com/pedrovgs/EffectiveAndroidUI.

You just have to review this packages to find some examples:

Your repo -> https://github.com/tonilopezmr/InteractorExecutor/tree/master/interactorexecutor/src/main/java/com/tonilopezmr/interactorexecutor

Pedro's repo: executor package-> https://github.com/pedrovgs/EffectiveAndroidUI/tree/master/app/src/main/java/com/github/pedrovgs/effectiveandroidui/executor

Your MainThreadImpl class -> https://github.com/tonilopezmr/InteractorExecutor/blob/master/interactorexecutor/src/main/java/com/tonilopezmr/interactorexecutor/MainThreadImp.java

Pedro's MainThreadImpl class -> https://github.com/pedrovgs/EffectiveAndroidUI/blob/master/app/src/main/java/com/github/pedrovgs/effectiveandroidui/executor/MainThreadImpl.java

Your ThreadExecutor class -> https://github.com/tonilopezmr/InteractorExecutor/blob/master/interactorexecutor/src/main/java/com/tonilopezmr/interactorexecutor/ThreadExecutor.java

Pedro's ThreadExecutor class -> https://github.com/pedrovgs/EffectiveAndroidUI/blob/master/app/src/main/java/com/github/pedrovgs/effectiveandroidui/executor/ThreadExecutor.java

My question is:

Instead of change the author of the code from `@author Pedro Vicente Gómez Sánchez` to `@author Antonio López` why don't you leave Pedro's author in your files or at least add a reference to Pedro's repository in your README.md as you've already done with @android10? 

Review EffectiveAndroidUI license, you have copy/pasted Pedro's implementation from a repository using an Apache License V.2 which requires attribution but you are not referencing Pedro's code from your repository.

Regards!

**Comment by android10** [comment]
Maybe I missed some documentation stuff. I do not have any problem with this, cause I worked with @pedrovgs in the same company and we got to this conclusion. You can read the article where I mention him and I also point to his repo:
http://fernandocejas.com/2014/09/03/architecting-android-the-clean-way/

**Comment by tonilopezmr** [comment]
You're absolutely right, but also you should read all this code:

https://github.com/glomadrian/MvpCleanArchitecture/tree/master/app/src/main/java/com/github/glomadrian/mvpcleanarchitecture/executor

https://github.com/JorgeCastilloPrz/EasyMVP/tree/master/app/src/main/java/com/github/jorgecastilloprz/easymvp/executor

When used the MVP We need to implement the Executor and Interactor, for that reason I write this library.

And I used the documentation of @pedrovgs because I think that his documentation is good, and my english is very very bad, :(.

If you read https://github.com/tonilopezmr/Android-EasySQLite, I mentioned some repositories when I learned the MVP.

Thanks for everything.

**Comment by joseantoniosantos** [comment]
@glomadrian and @JorgeCastilloPrz have a section in the README.md where they add some links to references used. You can do the same in the README.md of this repo :) As you are already doing with Android-EasySQLite, so I guess there is no problem adding a section to this repo :)

You should do it because Apache License V2 exposes is mandatory to have a reference to the library author to keep the attribution of the code you are using in your software, and you have extracted this code from that repository.

**Comment by tonilopezmr** [comment]
I didn't write in this README.md a section where I mentioned the repositories because already I wrote it in the EasySQLite README.md. But no problem, I add the section in this README.md.

Thanks for worrying .

**Comment by pedrovgs** [comment]
Do whatever you want with my code, the license is there you just have to read it to know what you can do with it. I publish code to be used and to share it with he community, that's the most important idea. 

Thanks for the attribution! But please, change your README.md, I've written more than your documentation in this repository.

**Comment by tonilopezmr** [comment]
Resolved
